# Configuration for calibration


# Board grid size
grid_size: [4, 13]

# Frame size
frame_size: [640, 480]

# Diameter
diameter: 20

# Enable results refinement
refine: false

# Path to the directory containing calibration images
images_path: data/calib_imgs

# Path to save the calibration parameters
save_path: weights
