# Configuration for camera


# Frame delay (millisecond)
delay: 1

# Process frequency
subsampling: 1

# Video resolution
resolution: null

# Record video
record:
  # Save destination
  path: records

  # Save resolution
  resolution: null

# Video debug
debug:
  # Show fps
  fps: true
