# Configuration for dataset generator


# -------
# Dataset

# Video folder path
data_path: data/data_gen/videos

# Save folder path
save_path: data/data_gen/dataset

# Save name (Default: using Date)
save_name: null

# Video subsampling
subsample: 3

# Train, val, test size
split_size: [0.7, 0.2, 0.1]

# Image size
image_size: 640

# Number of workers
num_workers: 0.6

# ------------
# AutoLabeling

# Rembg model. For more detail: https://github.com/danielgatis/rembg?tab=readme-ov-file#models
model: u2net

# Device for computing ('cpu' or 'cuda' or 'auto')
device: auto

# Using TensorRT (CUDA only)
tensorrt: false
