# Configuration for run.py



# Dataset
data:
  # Video folder path
  data_path: video

  # Video subsampling
  subsample: 3

  # Train, val, test size
  split_size: [0.7, 0.2, 0.1]

  # Image size
  image_size: 640

  # Number of workers
  num_workers: 0.6


# AutoLabeling
labeling:
  # Rembg model. For more detail: https://github.com/danielgatis/rembg?tab=readme-ov-file#models
  model: u2net

  # Device for computing ('cpu' or 'cuda' or 'auto')
  device: auto

  # Using TensorRT (CUDA only)
  tensorrt: false
