# Configuration for detection


# Model weight path
weight: weights/yolov8m.pt

# Confidence threshold for detection
conf: 0.25

# Intersection over Union
iou: 0.4

# Input size for the model
size: 640

# Use half precision (float16) for better inference
half: true

# Fuse model layer
fuse: true

# Using onnx model
onnx: false

# Use TorchDynamo, the latest method to speed up PyTorch code
optimize: true

# Backend to be used for model optimization
backend: null

# Device for computing ('cpu' or 'cuda' or 'auto')
device: auto
